### ISSUE TITLE
Account Ignores Empty Required Fields - Save Issues

### ISSUE THREAD

**Issue by LokiFrostGiant** [Speuce/JAMCo#116]
### Bug summary:
Not sure what else to call this bug. This bug occurs when a user passes OAuth and is brought to the account creation modal, then the page is refreshed, then the user logs in again. The user is marked as saved and complete and allowed to access the board.

There is a second bug. Settings menu does not enforce required fields and _saves all changes when clicking close_. 

### Bug details:
- User is saved upon refresh without clicking "Sign Up"
- Required fields are not required/verified upon refresh
- User can "login" without completing the login process
- Edit-mode in Settings menu can be closed without filling in the empty required fields

Feel free to add more bullets upon discovery if applicable.

**Comment by jaredwebber** [comment]
Looks pretty straightforward:
- For signup page, just check if user has any empty required fields - if so - show signup screen
- For settings modal, looks like the `save` button event toggle (between save/edit) needs to be re-linked with the field validation
